# Birds CUB dataset
birds_images_path: '/scratch/ak6384/final/text2image2textGAN/data/cvpr2016_cub/images/'
birds_embedding_path: '/scratch/ak6384/final/text2image2textGAN/data/cub_icml/'
birds_text_path: '/scratch/ak6384/final/text2image2textGAN/data/cvpr2016_cub/text_c10/'
birds_dataset_path: '/scratch/ak6384/final/text2image2textGAN/data/birds.hdf5'

val_split_path: '/scratch/ak6384/final/text2image2textGAN/data/cub_icml/valclasses.txt'
train_split_path: '/scratch/ak6384/final/text2image2textGAN/data/cub_icml/trainclasses.txt'
test_split_path: '/scratch/ak6384/final/text2image2textGAN/data/cub_icml/testclasses.txt'


# flowers dataset
flowers_images_path: '/scratch/ak6384/final/text2image2textGAN/data/flowers/flowers_images'
flowers_embedding_path: '/scratch/ak6384/final/text2image2textGAN/data/flowers/flowers_icml'
flowers_text_path: '/scratch/ak6384/final/text2image2textGAN/data/flowers/cvpr2016_flowers/text_c10'
flowers_dataset_path: '/scratch/ak6384/final/text2image2textGAN/data/flowers/flowers_v2.hdf5'

flowers_val_split_path: '/scratch/ak6384/final/text2image2textGAN/data/flowers/flowers_icml/valclasses.txt'
flowers_train_split_path: '/scratch/ak6384/final/text2image2textGAN/data/flowers/flowers_icml/trainclasses.txt'
flowers_test_split_path: '/scratch/ak6384/final/text2image2textGAN/data/flowers/flowers_icml/testclasses.txt'
